# ===================================================================
# VinFin Spring Cloud Config.
# ===================================================================

# Property used on app startup to check the config server status
configserver:
    name: VinFin Registry config server
    status: Connected to the VinFin Registry config server, using https://github.com/vunguyen-biglabs/vinfin-registry-config-dev !

# Default JWT secret token (to be changed in production!)
jhipster:
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
application:
    endorsementCount: 6
